name: CI + CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: echo Olá, Mundo!
        
  DeployDev:
    name: Deploy to Dev
    if: gituhb.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying!
        
  DeployStaging:
    name: Deploy to Stating
    if: gituhb.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Stating
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo Estou integrado na Homologação!
        
  DeployProd:
    name: Deploy to Production
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo Estou integrado na Produção!
